name: bloc_annotation
description: Generates the BLoC Boilerplate.
version: 0.0.2
author: Stephane Balasse <stephane.balasse@gmail.com>
homepage: https://github.com/stephanebalasse/bloc_built

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0
  meta: ^1.1.6

dev_dependencies:
  test: 1.3.4