name: bloc_built
description: A new Flutter project.
author: Stephane Balasse <stephane.balasse@gmail.com>
homepage: https://github.com/stephanebalasse/bloc_built

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: '>=0.32.2 <0.35.0'
  build: '>=0.12.6 <2.0.0'
  source_gen: ^0.9.0
  bloc_annotation: ^0.0.2
  code_builder: ^3.1.3
  path: ^1.3.2
  meta: ^1.1.6
  build_config: '>=0.2.6 <0.4.0'
  dart_style: ^1.2.2
  rxdart: ^0.20.0

dev_dependencies:
  test: 1.5.1+1

