name: bloc_built
description: A new Flutter project.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  source_gen: ^0.9.0
  bloc_annotation:
    path: ../bloc_annotation/
  code_builder: ^3.1.3
  path: ^1.3.2


dev_dependencies:
  test: 1.5.1+1
